### ISSUE TITLE
Fix old dependencies in Jekyll

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#106]
I'm getting some depandabot alerts about security vulnerabilities which can't be automatically resolved because of old dependencies. @philipbelesky could you please check whether we can update Jekyll to get this fixed?

![image](https://user-images.githubusercontent.com/49192999/159937309-7e5b112d-3bec-4606-8994-84af46a7127b.png)

**Comment by philipbelesky** [comment]
Should be fixed now, although it's difficult to verify without seeing the alerts. Let me know if you are still getting them!

**Comment by mariuszhermansdorfer** [comment]
Thanks. Everything is up to date now.

**Comment by mariuszhermansdorfer** [comment]
It turns out, that my previous reaction was a bit premature. Here are the security issues I can still see:

![image](https://user-images.githubusercontent.com/49192999/160103758-09e23ae7-40bc-4072-9042-2c3402c19c6d.png)
![image](https://user-images.githubusercontent.com/49192999/160103798-48eb9a51-5a2c-4296-b1a2-6eafa48b372f.png)
![image](https://user-images.githubusercontent.com/49192999/160103874-8c139c97-dfa7-478f-95a6-8cf3a2b6d0a0.png)

**Comment by philipbelesky** [comment]
I think these issues might be best left as a wontfix. The dependencies here are all 2nd or 3rd order, stemming from the `github-pages` gem and the version of Jekyll required to use Github pages. So, updates are going to be constrained at which those evolve. 

The 'vulnerability' here isn't really worth worrying about either as the actual dynamic parts of Jekyll are just used during builds - what Github serves up is just the static html files. If it's too annoying I could shift things over to Cloudflare Pages which would enable us to control dependency versions more precisely.

**Comment by mariuszhermansdorfer** [comment]
Thanks for looking into this. Let's leave it as is, if it's too much effort to solve.
