### ISSUE TITLE
Draw contour lines

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#15]
Drawing actual curves to display contour lines is computationally expensive. Let's try adding these in the shader instead. Simply change the vertex color value to black at a given interval in the Z direction.

**Comment by philipbelesky** [comment]
Some quick notes/research:

- Changing the vertex colors within elevations bands should be nominally quite quick, assuming that the array of pixels can be sorted quickly using `Array.Sort()`. Pretty sure C# uses quick sort under the hood, but if the sorting ends up being slow a bucket or radix sort might be potentially quicker as the sorting process mirrors what we intend to use the data structure for. 
- I wonder how computationally expensive a best-case contouring method that outlines polylines could be. I assume here that RhinoCommon's contour command is not using any of the below optimisations as it would have a need for higher accuracy:
    - A [marching squares algorithm](http://www.inf.ed.ac.uk/teaching/courses/vis/lecture_notes/lecture7.pdf) that can directly compute intersections within a scalar field / point grid 
    - A quadtree structure or an interval structure to [speed up marching squares processing](https://www.cse.wustl.edu/~taoju/cse554/lectures/lect05_Contouring_II.pdf)
    - The use of the existing mesh cache / look up table to only re-drawn contours when there are significant differences in state.
    - Parallelising, GPU-offloading, or using C to perform the above steps faster

**Comment by mariuszhermansdorfer** [comment]
Ad 1. I have just uploaded a [branch](https://github.com/mariuszhermansdorfer/SandWorm/tree/contours) where I doodled a bit with displaying contour lines as part of the vertex shader. It is fast, but visually quite disappointing... 
https://youtu.be/kjxylCEvV5M

We're probably better off looking into drawing actual polylines...

**Comment by mariuszhermansdorfer** [comment]
And btw. we need some better-looking gradients soon!
My eyes hurt each time I see these ultra-saturated rainbow on the screen :)

**Comment by mariuszhermansdorfer** [comment]
From the middle of [this video](https://youtu.be/0cUL_63J7xs) one can see the difference, proper curves make. It's worlds apart. Obviously, we'd need to internalize the logic. Having it run through an external component is way too slow.

**Comment by mariuszhermansdorfer** [comment]
Awesome @BarusXXX ! We should definitely use this as an immediate improvement.

Mid-term I'd like us to have a more interactive logic, though. I've found [this post](https://grgrdvrt.com/works/contour-lines/) with a nice description of how the algorithm works. To answer your questions, @BarusXXX, instead of creating isocurves from the mesh, we use the elevation array from the sensor and work directly on its values. 

For every pixel, we check the elevation delta to each neighbor and mark it with a dot. The placement of these dots is linearly interpolated -> difference between elevation values for neighboring pixels is '5', we place 4 dots at the corresponding edge and space them by edgeLength/5   
![image](https://user-images.githubusercontent.com/49192999/121170733-e71aca00-c855-11eb-8ac4-61e522705997.png)
 

Then it's just a matter of connecting the right dots (corresponding to the contour interval setting).

**Comment by mariuszhermansdorfer** [comment]
OK,
I took a stab at implementing the logic from the above post. Preliminary results are not too sexy yet, but I'll try to optimize it for one more day to see how feasible this approach is.  

![image](https://user-images.githubusercontent.com/49192999/129213450-2cc86f52-d648-4a03-9ef5-d9bd347f271a.png)

**Comment by mariuszhermansdorfer** [comment]
I like the fact, that we can decide on the density of the sampling grid for contour lines separately to the mesh. Here, I added a slider to define how coarse we want the analysis to be:

![image](https://user-images.githubusercontent.com/49192999/129233366-560515fc-27a6-4ba1-83e9-8b506938d184.png)

I haven't figured out a proper way of connecting these lines yet and didn't optimize the code at all, but already now it is the fastest we've ever had.

@philipbelesky, @BarusXXX do you have an idea on how to connect the lines? 

Right now, it's just a bunch of loose lines, and ideally we'd have one polyline per contour line.

**Comment by mariuszhermansdorfer** [comment]
Fixed some bugs in the contour lines logic - it looks like we can use this for fast & coarse interactive contour display, and let users generate more detailed contours once the mesh is baked.
![image](https://user-images.githubusercontent.com/49192999/129339098-bbcf1840-6ee3-4603-a7e6-d50d825ccfb2.png)
![image](https://user-images.githubusercontent.com/49192999/129338515-f3f9df4f-ef72-4e63-b58d-ae7b06b6cacd.png)

Still some work to be done on this front but looks potentially promising.

**Comment by mariuszhermansdorfer** [comment]
Getting there:
![image](https://user-images.githubusercontent.com/49192999/129458461-753d7ae8-3ea1-4a47-ac3a-0a5810c2463c.png)

**Comment by mariuszhermansdorfer** [comment]
@philipbelesky, @BarusXXX, I think we've got it! 
Displaying all the contour lines through the display pipeline (DrawViewportWires) rather than outputting them through the component speeds things up tremendously! Now, we really have an interactive model which is super fun to work with!

![image](https://user-images.githubusercontent.com/49192999/129460236-6279951c-52ff-44bf-a29f-f369fbb228b1.png)
![image](https://user-images.githubusercontent.com/49192999/129460239-ae2ed79d-6c20-4527-8e91-902a54ca49fa.png)

**Comment by mariuszhermansdorfer** [comment]
There might be value in having a dedicated contour lines output, though. Therefore, I added the following hybrid logic:

 - by default contour lines are being rendered through the display pipeline (DrawViewportWires). This is fast but doesn't allow for downstream reuse of any geometry:
![image](https://user-images.githubusercontent.com/49192999/129472445-2df3f1d9-f5c7-4adb-903c-353d8d5a00fd.png)

- if users connect anything to the `contours` output parameter, SandWorm switches to displaying real geometry, which is slower but potentially more fliexible:
![image](https://user-images.githubusercontent.com/49192999/129472536-789ce978-f82c-4f6e-ad5e-66f24e1a2c78.png)

I'm using the same trick for `water surface` rendering - the moment something is connected to the corresponding output, its display is turned off in the main component. We can't really use the typical GH approach of disabling the preview of the component, since it would force us to output contours as geometry as well and slow things down significantly.

![image](https://user-images.githubusercontent.com/49192999/129472615-86bd867d-5d11-4033-ab62-7997f34c3255.png)

**Comment by mariuszhermansdorfer** [comment]
Code ported to work with Kinect for Windows as well. It is super smooth and a joy to work with:
![image](https://user-images.githubusercontent.com/49192999/129604473-74778cbb-70c6-4a58-8041-e799c7a6147c.png)

**Comment by mariuszhermansdorfer** [comment]
Made contour lines adapt to Rhino's drawing units.

**Comment by philipbelesky** [comment]
As you mentioned, this is a joy to use! The lack of overhead in the component-preview mode is also great to see. 

Regarding the geometric output, I assume the latency is coming from the sheer amount of `Line` objects that are being output? In which case it might be worth trying to use `GH_Line` rather than `Line` to see if type conversions can be avoided. The other trick is that changing the output parameter to be `Generic` rather than `Curve` can often route around conversion issues.

Another option might be to test if the overhead of joining the lines together might be similar/less to the overhead of outputting so many lines individually. As a bonus, it could open up some nice opportunities in the component to bridge some of the transient 'gaps' between lines as well as making downstream operations (e.g. further smoothing or contour 'matching') easier.

I've slightly run out of time today just reading/testing the new code but would be happy to have a go at some of the above options.

**Comment by mariuszhermansdorfer** [comment]
Definitely, way too many lines to output for Grasshopper to remain interactive. I took a stab at creating `Polyline` object rather than lines using two linked `Dictionary<Point3d, Polyline>`. One for start points, the other for end points. I got to a point, that roughly half of the lines were connected, couldn't figure out how to solve the issue, got annoyed and deleted the code :)

Would be great if you could test the proposed solutions, I might also revisit my idea another day with a fresh brain.

**Comment by philipbelesky** [comment]
Ah, thanks for trying that out. Should we close this issue and could come back to joining/linking as a separate issue?
