### ISSUE TITLE
Provide pre-defined colormaps

### ISSUE THREAD

**Issue by philipbelesky** [mariuszhermansdorfer/SandWorm#19]
This would be pretty far down the list of priorities, but I thought I'd put it out there while I have the link in front of me. Google has published a [colormap library](https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html) for depth images that more uniformly maps between color bands and spatial bands. In an ideal world the gradient used to color the pixels would be entirely user-controlled, but this might be an interesting option to consider as a robust default.

**Comment by mariuszhermansdorfer** [comment]
Yeah, we definitely need some better looking color ramps. The one currently used was just the easiest to generate by I don't really like the way it looks. I'd like to have a library of more 'landscapy' gradients such as these:
[example 1](https://www.ravenmaps.com/mm5/graphics/00000001/pennsylvania_nj_topographical.jpg)
[example 2](https://www.ravenmaps.com/mm5/graphics/00000001/washington_elevation_large.jpg)
[example 3](https://www.researchgate.net/profile/Bernhard_Jenny/publication/317391414/figure/fig6/AS:668594480353281@1536416754128/An-example-of-a-natural-color-map-created-by-Stengel-in-1850-using-pencil-pen-and.png)

Some more theory on color ramps [here](https://www.researchgate.net/publication/317391414_Natural-color_Maps_via_Coloring_of_Bivariate_Grid_Datal) and [here](http://www.shadedrelief.com/hypso/hypso.htmll)

**Comment by mariuszhermansdorfer** [comment]
Relabeled this issue to reflect a broader scope.

**Comment by mariuszhermansdorfer** [comment]
SandWorm 2.0 now has a few pre-defined color maps for the elevation analysis, as well as the option to provide a user-defined color list:

Chile:
![image](https://user-images.githubusercontent.com/49192999/129478208-88b0dc30-9bb9-4e9b-9f2c-0d6f6b67e6f8.png)

Desert:
![image](https://user-images.githubusercontent.com/49192999/129478213-06fef4e6-b161-4314-bcb6-7331f7687121.png)

Europe:
![image](https://user-images.githubusercontent.com/49192999/129478216-b6b52f7b-e43f-4635-aaf5-076f68e040c0.png)

Greyscale:
![image](https://user-images.githubusercontent.com/49192999/129478218-8b69ed4e-3afa-4f43-8087-0721ec13757c.png)

Mars:
![image](https://user-images.githubusercontent.com/49192999/129478642-2cd91ee7-da63-46e7-9e7c-63bdcfc7f1ed.png)

Ocean:
![image](https://user-images.githubusercontent.com/49192999/129478224-c083b710-b689-42a2-b538-48690e39cf30.png)

Rainbow:
![image](https://user-images.githubusercontent.com/49192999/129478229-d07ff75a-355a-4fa8-83ea-fbb701560c3f.png)

Custom:
![image](https://user-images.githubusercontent.com/49192999/129478237-ddc2e5ac-36ff-447d-9fff-33512de7e176.png)

Of course, everything works with contour lines display as well:
![image](https://user-images.githubusercontent.com/49192999/129478659-67c53a73-feb3-4e94-a343-fedd85757bdb.png)


@BarusXXX, @philipbelesky let me know if you can recommend any sources for good quality landscape color palettes.

**Comment by philipbelesky** [comment]
Love the names here! I've added the struct for the Turbo palette from one of my links above. That uses about 14 steps though, so I'll rewrite the lookup table code to handle dynamic ranges for steps and send that through as a PR.

**Comment by mariuszhermansdorfer** [comment]
Perfect! 
Regarding naming patterns - I started with `Mars`, but then saw the opportunity and renamed it to `Dune`. 
Now the plugin is complete.
