### ISSUE TITLE
Create a separate component outputting the point cloud

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#24]
As mentioned in #1 - we need a dedicated SW component outputting the point cloud

**Comment by mariuszhermansdorfer** [comment]
Note to self:
Point Cloud: https://discourse.mcneel.com/t/grasshopper-pointcloud-on-xyz-grid-c/53571/10
DrawViewportWires: https://discourse.mcneel.com/t/can-drawviewportwires-draw-gh-objects/77494/5

**Comment by philipbelesky** [comment]
So maybe there should be a parameter on that component (defaulting to off) that writes out a `Point3D` list if people ever need to manipulate the points further in Grasshopper? 

Another option would be to check in with Cam and see if he wouldn't mind us employing the same methods [as Tarsier](https://bitbucket.org/camnewnham/tarsier/src/master/). There would be quite a bit of value in using their `GH_PointCloud` class and being able to interoperate with their modification/search components.

**Comment by mariuszhermansdorfer** [comment]
I reached out to Cameron a few weeks ago regarding this. Don't know whether he knew, that you are part of the project at that time, but was still very open to us reusing his code.

Outputting a `Point3d` list is the slowest possible option. Much better to cast to `GH_Point` and spit these out. Cameron has posted some extensive test results in [this thread](https://discourse.mcneel.com/t/update-rhino-geometry-in-real-time-from-a-c-component/80635/2).

**Comment by philipbelesky** [comment]
![PC](https://user-images.githubusercontent.com/495961/67456702-52ae2480-f67d-11e9-98f8-c13b41274bd9.png)

Basic point cloud output works, although that was a very quick change. Getting the RGB colors and/or coloring the pixels based on analysis will need a bit more work. 

Most of the work here has thus far been in trying to abstract out the shared methods between the new and old component. For that reason the merge-in for this one will be somewhat tricky, but new classes will allow me to start making some progress on #25 that should also illuminate how to handle the pixel-coloring in this case as well.  

Regarding tarsier and their `GH_PointCloud` class, as tarsier is GLPv3 we would need to re-license Sandworm to match if the code was included. Would that be OK with you?
