### ISSUE TITLE
Create a separate component for RGB/QR code token isolation

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#25]
As mentioned in #1 we need a dedicated component for RGB/QR code token isolation

**Comment by philipbelesky** [comment]
Thanks for adding the 'image' texture view. This is just a quick note that I intend to dig up my old branch for this and get the prototype working again. We could then talk about if it should be kept as a distinct component or integrate it into the main one.

**Comment by philipbelesky** [comment]
In a similar vein, keyboard shortcuts could be useful and perhaps open up other forms of controller - e.g. in an 'ideal' exhibition setup a [streamdeck or similar](https://www.elgato.com/en/stream-deck-mk2) would be ideal!
