### ISSUE TITLE
Cache color lookup tables across definition solves

### ISSUE THREAD

**Issue by philipbelesky** [mariuszhermansdorfer/SandWorm#30]
Currently the `ComputeLookupTables` methods of each analysis option are calculated each time the definition solves which seems inefficient. To cache the values we will need to track the relevant user parameters that could alter the table (i.e. `sensorheight`, `waterlevel`) and only re-compute the tables if a relevant parameter changes. Each class inheriting from `MeshVisualisation` will likely have a distinct logic for doing so as they depend on different inputs (or none at all in the case of slope/aspect).

**Comment by mariuszhermansdorfer** [comment]
When working on this issue, please consider #33, which I just opened. It could address the troubles we had with implementing water as part of the mesh shader.
