### ISSUE TITLE
Draw waterLevel as a plane rather than part of the mesh color

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#33]

**Comment by mariuszhermansdorfer** [comment]
Current implementation of waterLevel being part of mesh coloring logic is causing some headache. Why don’t we implement it as a separate object (a plane?) whose visibility would be toggled by our existing right click menu option?

I was never really happy with the visual quality of our current approach. Having a separate water plane would allow us to assign a custom material to it with proper opacity, absorption and maybe even bump. Dunno how fast these things would render but it’s still worth giving a shot.

**Comment by philipbelesky** [comment]
That would definitely simplify the implementation, I can make the change as part of the other reworkings of the analysis classes.

**Comment by philipbelesky** [comment]
Closing as this was completed as part of #34. I never noticed it take more than 0ms so there shouldn’t be any concerns with performance. Feel free to reopen if there are any questions or improvements for the implementation.
