### ISSUE TITLE
Create an icon set

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#36]
As simple as that - we need a set of icons for our components.

**Comment by philipbelesky** [comment]
And maybe a logo for the project as a whole? Both for marketing purposes and as an icon the splash screen that loads with Grasshopper. If you're fine with the styles being so close, I could [do a groundhog style silhouette](https://camo.githubusercontent.com/535c4a5905dc41e8bfb14753602495228c092863/68747470733a2f2f63646e2e7261776769742e636f6d2f7068696c697062656c65736b792f67726f756e64686f672f646576656c6f702f736974652f6173736574732f6c6f676f2e737667) of a sandworm pretty easily.

For the actual component icons I have an `.ai` file with the original Grasshopper icons that I can pass on — in some cases elements could be reused/adapted in the new icons.

**Comment by mariuszhermansdorfer** [comment]
I like the Groundhog logo a lot. It would be great if we could have something in equally high visual quality. Now the question is - how do SandWorms actually look like? I like the simple take of this representation:
http://www.ou.edu/class/FRINFO/GTA/EGO/Gifs/Personal/sandworm.gif

**Comment by philipbelesky** [comment]
Some [additional research here](https://dune.fandom.com/wiki/Sandworm). The H.R. Geiger take is appropriately terrifying, but I suspect the three-part-mouth version has a better silhouette!

**Comment by mariuszhermansdorfer** [comment]
Saw your sketch in #37. Here is my take on it. Tried to convey a somewhat digital and mesh-related nature of our puppy. Not sure whether this will work when smaller, though. Thoughts?
![image](https://user-images.githubusercontent.com/49192999/65462812-d8f50200-de56-11e9-8d56-9cc025bb9750.png)
![image](https://user-images.githubusercontent.com/49192999/65462845-e3170080-de56-11e9-9ecf-62187061cd87.png)

**Comment by philipbelesky** [comment]
Yea, I guess it does depend on where it is going to end up being used. The Groundhog silhouette approach came out of it primarily being displayed in the website header and as a favicon. The full-size version is only ever shown in the README. 

That said, a README is all Sandworm has at the moment, so we could add your version to the logo.ai file and consider a switch/revision down the track if there is a need for a small version?
