### ISSUE TITLE
MVP for Release 1.0

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#42]
@philipbelesky, @BarusXXX let's define the minimum product we want to release as version 1.0 and start working towards a deadline sometime in October maybe?

I have combed through the list of open issues and labeled some with a corresponding milestone tag. Feel free to add to it and assign yourself to whichever suit your fancy.

Edit:
Created a [Kanban style board](https://github.com/mariuszhermansdorfer/SandWorm/projects/1) to better track the progress. While creating new issues, just assign these to the relevant project.

**Comment by philipbelesky** [comment]
Sounds good! A 1.0 would also be a good point to publish a package on [Yak](http://developer.rhino3d.com/guides/yak/what-is-yak/). I've set this up for Groundhog so can do so here, although we should consider whose Rhino account it would be tied to, or create a new shared one.

**Comment by mariuszhermansdorfer** [comment]
Creating a shared Rhino account would be the cleanest solution IMHO. 
Better yet, could we create a [team](https://accounts.rhino3d.com/help#groups), link our existing accounts and use it to publish to Yak. Not sure whether this is how things work, though.
