### ISSUE TITLE
Add a component for robotic arm interaction

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#48]
During our recent PhD workshop Kane operated a robotic arm to form the sand in the box. It would be great to create a dedicated component allowing for an intuitive plug-and-play type of interaction with the UR robots.

![image](https://user-images.githubusercontent.com/49192999/65830143-073a6d80-e2ad-11e9-8e8d-8fd281ac153b.png)

**Comment by philipbelesky** [comment]
I haven't used the robotic arms in this case, but is there a need for sandbox-specific code to control the robot? Or would one of the existing plugins for robotic control be sufficient? It seems like a large increase in the scope of the plugin.

**Comment by mariuszhermansdorfer** [comment]
Agreed. Having run a few workshops on this topic and it makes more sense to leverage external logic for robotic arm interaction.

Closing this for now.
