### ISSUE TITLE
Remove hardcoded assumption about Kinect depth range

### ISSUE THREAD

**Issue by philipbelesky** [mariuszhermansdorfer/SandWorm#7]
Line 149 of `SandwordComponent.cs` contains the condition:

    if (p.Z > dep || p.Z < 1.0)

This was a stumbling block in getting the model operating as the `<1.0` was culling a bunch of points that contained the relevant parts of the cloud. Does 1.0 have any particular meaning in terms of units? Maybe this is because I had the model further/closer than I should?

Anyway, it seems like the ideal way to provide a depth cull would be to provide either a depth min and depth max parameter, or to accept a Domain. Not sure what the best approach is and it might be worth implementing alongside #1 - if not I'm happy to add a PR for it.

**Comment by mariuszhermansdorfer** [comment]
Sorry about that, should have been clearer while sending the code over. It is definitely a good idea to allow users to define a range they are interested in. In my setup, the Kinect is 1.4 meters above the table, culling anything < 1.0 meter made sense and helped me get rid of the flying pixels as well.

Domain seems to be an elegant solution.

**Comment by mariuszhermansdorfer** [comment]
Removed this functionality for now. The way meshing is handled now, it makes more sense to operate on the entire array of depth pixels and trim it only in the X Y dimensions.
