### ISSUE TITLE
Reconsider UI presentation of reset and calibrate

### ISSUE THREAD

**Issue by philipbelesky** [mariuszhermansdorfer/SandWorm#88]
This is extremely nit-picky and low-priority, but I find that the reset / calibrate options as presented in the UI are slightly confusing and might be difficult for new users to grasp. 

Unless I'm wrong, the calibrate method is essentially a one-time trigger, e.g. it samples the latest frame and averages the values to identify a good elevation number. However, as presented in the UI, the button is a checkbox which would normally indicate some sort of boolean state that is persistent. 

The reset action is also a one-time trigger, but is presented in a different way: as a boolean input type. Although it has some help text, it may not be apparent to all users that the `Button` component is what's needed to trigger the action.

A suggestion here would be to shift both of those triggers to be shown in the same way, perhaps as buttons within the *Sensor* rollout. That could also be useful to clarify the role of the reset button as re-setting-up the mesh processing rather than a 'clear to defaults' for the parameters of the analysis/processing/etc.

It doesn't look like there's a button widget in `CustomComponent` but I could try and adapt the one I made for Caribou perhaps.

**Comment by mariuszhermansdorfer** [comment]
You're absolutely right. The cleanest way of solving this from an UI perspective, would be to have 2 dedicated buttons to perform their respective functions. The only reason, why I didn't do it the way you suggested, was that I was to lazy to write my own `Button` widget for the `CustomComponent`. Would be great if you gave it a go, though!

**Comment by mariuszhermansdorfer** [comment]
@philipbelesky thanks for pushing the latest commit! 

Did you find time to work on the button functionality? It would be great to add this to the UI and finally publish the plugin for wider use. Let me know if you won't be able to work on this, so that I can give it a go myself.

**Comment by philipbelesky** [comment]
Ah, I had forgotten about this one. I think i'll have a go at it over the next week to try and get a better handle on the `CustomComponent` workings. I'm planning to get back into the image recognition branch shortly as well.

**Comment by mariuszhermansdorfer** [comment]
Awesome! Let's aim for early February to publish the 2.0 version with minor tweaks to the UI. Then, the image recognition functionality could be added as 2.1 when ready.
