### ISSUE TITLE
Agent Behavior

### ISSUE THREAD

**Issue by BarusXXX** [mariuszhermansdorfer/SandWorm#90]
Add a simple agent simulation that randomly places agents on the periphery and gives each agent a random destination. 
Using the slope analysis agents as data agents should wander to their destinations preferring more walkable slopes along the way.
This could later be elaborated to make use of the data the sensor collects.

**Comment by philipbelesky** [comment]
I feel that for most analysis/simulation ideas, we should err on the side on assuming they are better done downstream unless there is a specific reason they need to happen within the render loop. Downstream, users have much more control and can use fully-featured components that are designed for specific purposes, whereas any in-Sandworm analysis is going to be limited in what it control and how much it can be parameterised. Is there a case for agent modelling needing to be integrated into the main component, or being substantially better for being integrated?

**Comment by BarusXXX** [comment]
Fair point, I was more thinking of it as an interesting visual aid to run during onsite interaction rather then its usefulness per se, I do agree that downstream analysis might be the best answer for this. However we need to be outputting usable data #89  from the analysis chosen for that to be the case. Outputting the whole array is one way... another is to prescribe which analysis points you want fetched and the component will fetch elevation, slope, head of water, flowline, aspect for the list of probe points the user supplies.
