### ISSUE TITLE
Sandworm as Rhino plugin

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [mariuszhermansdorfer/SandWorm#96]
@philipbelesky, @BarusXXX I recently started looking into Rhino plugin development to develop my skills further. 

Would you see any benefit in converting SandWorm from Grasshopper to Rhino? Would it lower the bar for students' adoption, or just kill the purpose of introducing them to a wider set of computational design tools?

Am curious to hear your take on it.

As a side note, here are my early doodles with custom UI styling for Rhino panels. Let me know if you'd like to use it for some of your projects:

https://user-images.githubusercontent.com/49192999/151328825-416e2f33-9a9a-42e8-aad4-41928370eeab.mp4

https://www.youtube.com/watch?v=C5XCSBKfMEY

**Comment by philipbelesky** [comment]
For my purposes, the most interesting benefit would be if it improves performance and the possibility that the extra overhead might enable more complex real-time simulation. 

For public-facing uses the lack of Grasshopper extensibility wouldn't be a major impact,  although I'm assuming rewriting logic from Grasshopper plugins to Rhino plugins isn't particularly difficult. Alternately, the output of the plugin could probably be referenced into Grasshopper just at a slight remove - e.g. using a Geometry Pipeline perhaps.

**Comment by mariuszhermansdorfer** [comment]
Not sure about how much more we can improve the performance. It's already quite streamlined and the most we can expect to shave off are just a few ms.  

In terms of additional simulation ideas - what are you thinking about?
